### ISSUE TITLE
[Warn/Ban Request] RepZ

### ISSUE THREAD

**Issue by MrAmos123** [XLabsProject/master#314]
GodSend/SAN has now been removed from the server list. Thank you.

Please can you apply the same to RepZ, or at least warn them about their bot's counting as players.

If not, then we'll get some 'bots' added to our servers.

![image](https://user-images.githubusercontent.com/4959320/185975891-b20b3bf7-5c5f-4868-9551-fab7426a906f.png)

**Comment by MrAmos123** [comment]
I wasn't sure where else to post this for ban requesting.

**Comment by diamante0018** [comment]
Xlabs administrators have the tools to take actions against these infractions don't worry. We are aware of the repz situation :)
Staff members regularly check the server list as normal players so we will notice.

**Comment by MrAmos123** [comment]
Alright perfect. Thanks very much, diamante! :)
